Document: debpackaging
Title: Debian debpackaging Manual
Author: <insert document author here>
Abstract: This manual describes what debpackaging is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/debpackaging/debpackaging.sgml.gz

Format: postscript
Files: /usr/share/doc/debpackaging/debpackaging.ps.gz

Format: text
Files: /usr/share/doc/debpackaging/debpackaging.text.gz

Format: HTML
Index: /usr/share/doc/debpackaging/html/index.html
Files: /usr/share/doc/debpackaging/html/*.html
